// ================================================================
//  EDIT THIS FILE — Replace with your real class student list
//  Each name should be the full display name as you want it shown
// ================================================================

export const STUDENTS: string[] = [
  "Iman Jabbar",
  "Rana Muhammad Ahmad",
  "Laiba Nadeem",
  "Humair Shehzad",
  "Sufyan Shahid",
  "Muhammad Zaid",
  "Khizer Ahmad",
  "Wajeeha Zahid",
  "M.Abdullah",
  "Muhammad Mujtaba",
  "Mariam Asim",
  "Muhammad Ahmad",
  "Mehak Kanwal",
  "Fazila Ashraf",
  "Abdul Ahad",
  "Abdul Muheet",
  "Muhammad Salman",
  "Wania Sarfraz",
  "Hassan Rafiq",
  "Ruhab Ahmad",
  "Muhammad Afnan Wajid",
  "Anusha",
  "Minahil Javed",
  "Hania Waqar",
  "Mahrukh Shahzad",
  "Maleeka Javaid",
  "Muhammad Uzair",
  "Abu Huraira",
  "Aima Zaheer",
  "Nafeesa Shahid",
  "Mohsin Iqtidar",
  "Zamzam Amir",
  "Afzal Hussain",
  "Kanzul Imaan Khalid",
  "Salman Haider",
  "Soha Ishtiaq",
  "Manahil Batool",
  "Hira Batool",
  "Hassan Ali",
  "Areesha Saleem",
  "M. Umer Shabbir",
  "Minahil Afzaal",
  "Rana Rizwan",
  "M.Zain Khalid",
  "Hufsa Noor",
  "Umar Lodhi",
  "Gulam Murtaza",
  "Saman Waseem",
  "Momina Arshad",
  "Zainab Raza",
  "Malik Hassan Nadeem",
  "Ayesha Naeem",
  "Saba Arif",
  "Muhammad Faraz",
  "Sana Shabbir",
  "Sahiba Ikram",
  "Dua Fayyaz",
  "M.Faizan",
  "Momina Shakeel",
  "Minahil Khalid",
  "Noor ul Eman",
  "Syed M. Junaid Bukhari",
  "Abdullah Khan Kakkar",
  "Bisma Mehmood",
  "Bilal Naseer",
  "Fatima Saleh",
  "Shahzaib Ahmad",
  "Nisar Akhtar",
  "Ahmad Awan",
  "Fareeha Iqbal",
  "Zainab Awais",
  "Talha Nasir",
  "Iraj Imran",
  "Moattar Khanam",
  "Naziha Malik",
  "Amna Amjad",
  "Humaira Fatima",
  "Maria Riaz",
  "Komal Muqaddas",
  "Sajal Ali",
];

// ================================================================
//  After editing, run:  npm run seed
//  This will create Supabase accounts for every student above
//  and generate generated-credentials.csv with their passwords.
// ================================================================
